name: Generate Table of Contents

on:
  push:
    branches:
      - '**' 

jobs:
  generate-toc:
    name: Generate Table of Contents
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3

    
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' 
     
      - name: Install markdown-toc
        run: npm install -g markdown-toc

      
      - name: Generate TOC
        run: |
          for file in $(find docs -name "**.md"); do
            markdown-toc -i "$file"
          done

     
      - name: Commit and push changes
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-generate Table of Contents" || echo "No changes to commit"
          git push
