name: Generate Table of Contents

on:
  push:
    branches:
      - '**'
jobs:
  generate-toc:
    name: Generate Table of Contents
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate Table of Contents
        uses: technote-space/auto-toc@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-generate Table of Contents" || echo "No changes to commit"
          git push
